on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: echo working directory
        run: echo ${{ inputs.working-directory }}
      
      - name: conditional step, only run on production.
        if: ${{ inputs.environment }} == "production"
        run: echo "we should be on production right now."