on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      environment:
        requireD: true
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: echo working directory
        run: echo ${{ inputs.working-directory }}